In [2]:
import numpy as np
import numpy.linalg as la

In [3]:
a=np.array([1,3,5,7,9],dtype='int32')
b=np.array((2,4,6,8),dtype='float32')
print(a)
print(b)
print(type(a)," ",type(b))
print(a.dtype," ",b.dtype)

[1 3 5 7 9]
[2. 4. 6. 8.]
<class 'numpy.ndarray'>   <class 'numpy.ndarray'>
int32   float32


In [4]:
a=a.astype('int8')
b=b.astype('int16')
print(a)
print(b)
print(type(a)," ",type(b))
print(a.dtype," ",b.dtype)

[1 3 5 7 9]
[2 4 6 8]
<class 'numpy.ndarray'>   <class 'numpy.ndarray'>
int8   int16


In [5]:
arr2d=np.array([[1,2,3],[4,5,6]])
print(arr2d.ndim)
print(arr2d.shape)
arr2d[0,2]

2
(2, 3)


3

In [6]:
print(arr2d.size)
print(arr2d.nbytes)
n=int(arr2d.nbytes/arr2d[0,0].nbytes)
print(n)

6
48
6


In [7]:
A=np.arange(100)
B=np.arange(20,50,3)
print(A)
print()
print(B)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

[20 23 26 29 32 35 38 41 44 47]


In [8]:
P=np.random.permutation(np.arange(10))
print(P)
x=np.random.randint(20,30)
print(x)

[1 4 2 9 3 7 0 8 6 5]
28


In [9]:
AA=np.random.rand(10)
print(AA)
BB=np.random.rand(2,3)
print(BB)

[0.82815284 0.05556379 0.31474899 0.79980843 0.46122384 0.91297509
 0.89747447 0.89398667 0.05403691 0.13399533]
[[0.8751271  0.74108492 0.81758031]
 [0.75965795 0.68250733 0.45787187]]


In [10]:
D=np.arange(100).reshape(10,10)
print(D)
print()
D=D.reshape(2,5,10)
print(D)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]
  [20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47 48 49]]

 [[50 51 52 53 54 55 56 57 58 59]
  [60 61 62 63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76 77 78 79]
  [80 81 82 83 84 85 86 87 88 89]
  [90 91 92 93 94 95 96 97 98 99]]]


In [11]:
I=np.arange(100)
I

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [12]:
ind=np.argwhere(A==11)[0][0]
ind

11

In [13]:
A = np.round(10*np.random.rand(5,5)).astype('int32')
print(A)

[[ 4  5  8  8  4]
 [ 8  5  3  2  6]
 [ 6  8  6  9  7]
 [ 1  3  7  0  6]
 [ 5 10  4  6  1]]


In [14]:
A.T

array([[ 4,  8,  6,  1,  5],
       [ 5,  5,  8,  3, 10],
       [ 8,  3,  6,  7,  4],
       [ 8,  2,  9,  0,  6],
       [ 4,  6,  7,  6,  1]], dtype=int32)

In [15]:
la.inv(A)

array([[ 0.13643555,  0.19329921, -0.15839926, -0.09799907, -0.00874826],
       [-0.15588646, -0.06328525,  0.05956259,  0.07445323,  0.13959981],
       [ 0.18548162,  0.0233597 , -0.18669148,  0.06663564,  0.02494183],
       [ 0.04932527, -0.06654258,  0.12145184, -0.0981852 , -0.05909725],
       [-0.16119125, -0.0278269 ,  0.21442531,  0.06803164, -0.09744067]])

In [18]:
print(A)
A.sort(axis=0)
print(A)
A.sort(axis=1)
print(A)

[[ 0  1  1  3  3]
 [ 2  4  4  4  5]
 [ 5  5  6  6  6]
 [ 6  6  7  8  8]
 [ 7  8  8  9 10]]
[[ 0  1  1  3  3]
 [ 2  4  4  4  5]
 [ 5  5  6  6  6]
 [ 6  6  7  8  8]
 [ 7  8  8  9 10]]
[[ 0  1  1  3  3]
 [ 2  4  4  4  5]
 [ 5  5  6  6  6]
 [ 6  6  7  8  8]
 [ 7  8  8  9 10]]


In [23]:
A[[1,2,4]]

array([[ 1,  1,  3],
       [ 4,  4,  5],
       [ 5,  6,  6],
       [ 6,  7,  8],
       [ 8,  8, 10]], dtype=int32)

In [24]:
A[A<8]

array([0, 1, 1, 3, 3, 2, 4, 4, 4, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7],
      dtype=int32)

In [43]:
A[(A<8)&(A>4)]

array([5, 5, 5, 6, 6, 6, 6, 6, 7, 7], dtype=int32)

In [46]:
A+=1
A

array([[ 2,  3,  3,  5,  5],
       [ 4,  6,  6,  6,  7],
       [ 7,  7,  8,  8,  8],
       [ 8,  8,  9, 10, 10],
       [ 9, 10, 10, 11, 12]], dtype=int32)

In [51]:
A=np.ones((2,3))
B=np.zeros((2,2))
C=np.hstack((A,B))
print(C)
D=np.zeros((4,3))
E=np.vstack((A,D))
print(E)

[[1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [52]:
B=np.random.rand(100000)
%timeit sum(B)
%timeit np.sum(B)

6.72 ms ± 55.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
30.8 µs ± 126 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
